name: Main
on: push
jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Terraform Validate
        shell: bash
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: |
          TF_VAR_access_key="$AWS_ACCESS_KEY"
          TF_VAR_secret_key="$AWS_SECRET_KEY"
          TF_VAR_region="us-east-1"
          TF_VAR_environment="test"
          TF_VAR_domain="example.com"
          TF_VAR_keybase_username="username"

          # terraform is available in the GitHub Actions virtual environment
          cd infra-terraform
          make init validate
