name: Main
on: push
jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Configure Terraform
        working-directory: ./infra-terraform
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: |
          echo "access_key       = \"$AWS_ACCESS_KEY\"" >  terraform.tfvars
          echo "secret_key       = \"$AWS_SECRET_KEY\"" >> terraform.tfvars
          echo 'region           = "us-east-1"'         >> terraform.tfvars
          echo 'environment      = "test"'              >> terraform.tfvars
          echo 'domain           = "example.com"'       >> terraform.tfvars
          echo 'keybase_username = "username"'          >> terraform.tfvars
      - name: Validate Terraform
        working-directory: ./infra-terraform
        run: |
          terraform init -backend=false
          terraform validate
