name: Main
on: push
jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set Terraform Variables
        shell: bash
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: |
          cd infra-terraform
          echo "access_key       = \"$AWS_ACCESS_KEY\""  >  terraform.tfvars
          echo "secret_key       = \"$AWS_SECRET_KEY\""  >> terraform.tfvars
          echo 'region           = "us-east-1"'          >> terraform.tfvars
          echo 'environment      = "test"'               >> terraform.tfvars
          echo 'domain           = "example.com"'        >> terraform.tfvars
          echo 'keybase_username = "username"'           >> terraform.tfvars
      - name: Terraform Validate
        shell: bash
        run: |
          # terraform is available in the GitHub Actions virtual environment
          cd infra-terraform
          make init validate
